fix bin scripts

diff --git a/bin/check_release b/bin/check_release
--- a/bin/check_release
+++ b/bin/check_release
@@ -1,12 +1,17 @@
 #!/bin/bash
 #
-# This script checks whether the version defined in pyproject.toml corresponds to the
-# to-be-released version in the CI pipeline.
+# This script checks whether the version defined in pyproject.toml and CHANGELOG.md
+# corresponds to the to-be-released version in the CI pipeline.
 
 set -e
 
+changelog_version=$(sed '3q;d' CHANGELOG.md \
+    | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*[^"]*\).*$/\1/')
+
 package_version=$(cat pyproject.toml | grep ^version | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*[^"]*\).*$/\1/')
 
-release_version="${CI_COMMIT_REF_NAME}"
+release_version="${TRAVIS_COMMIT}"
+
+if [ "${package_version}" != "${release_version}" ]; then (echo "ERROR: Version mismatch (${changelog_version} != ${release_version})"; exit 1) fi;
 
 if [ "${package_version}" != "${release_version}" ]; then (echo "ERROR: Version mismatch (${package_version} != ${release_version})"; exit 1) fi;
